<script setup lang="ts">
import {computed,nextTick,onMounted,ref} from 'vue';
import {request} from '../api';
import EmptyState from './ui/EmptyState.vue';
type RecordItem={id:number;category:string;title:string;content:string;occurredOn:string;status:string;feedback?:string;previousId?:number;replacedBy?:number};
type Score={id:number;subject:string;examName:string;score:number;fullScore:number;occurredOn:string};
type Data={dimensions:Record<string,number|null>;growthIndex:number|null;scores:Score[];records:RecordItem[];activities:{id:number;activityDate:string;activityType:string;detail:string}[];evaluations:{periodStart:string;periodEnd:string;evidence:string}[];skills:{id:number;skillName:string;score:number;level:string;occurredOn:string;evidence:string}[]};
const today=new Date().toLocaleDateString('en-CA'),from=ref(`${today.slice(0,4)}-01-01`),to=ref(today),data=ref<Data>(),loading=ref(false),busy=ref(false),error=ref(''),notice=ref(''),subject=ref('');
const form=ref({category:'ACTIVITY',title:'',content:'',occurredOn:today,requestKey:crypto.randomUUID()});
const previousId=ref<number|null>(null),revisionTitle=ref<HTMLInputElement>();
async function revise(record:RecordItem){if(busy.value)return;previousId.value=record.id;form.value={category:record.category,title:record.title,content:record.content,occurredOn:record.occurredOn,requestKey:crypto.randomUUID()};await nextTick();revisionTitle.value?.focus();}
const labels:Record<string,string>={PENDING:'待审核',APPROVED:'已通过',RETURNED:'需补充'},axes=[{key:'moral',label:'品德'},{key:'skill',label:'技能'},{key:'thinking',label:'思维'},{key:'smart',label:'智行'}];
const subjects=computed(()=>[...new Set(data.value?.scores.map(s=>s.subject)||[])]);
const scores=computed(()=>data.value?.scores.filter(s=>s.subject===subject.value)||[]);
const complete=computed(()=>data.value && axes.every(a=>data.value!.dimensions[a.key]!=null));
const radar=computed(()=>axes.map((a,i)=>{const v=Number(data.value?.dimensions[a.key]||0)*.8;return `${120+Math.sin(i*Math.PI/2)*v},${120-Math.cos(i*Math.PI/2)*v}`;}).join(' '));
const trend=computed(()=>scores.value.map((s,i)=>`${30+i*400/Math.max(1,scores.value.length-1)},${170-s.score/s.fullScore*140}`).join(' '));
let generation=0;
async function load(){const current=++generation;loading.value=true;error.value='';try{const result=await request<Data>(`/student-portal/growth?from=${from.value}&to=${to.value}`);if(current!==generation)return;data.value=result;if(!subjects.value.includes(subject.value))subject.value=subjects.value[0]||'';}catch(e){if(current===generation)error.value=(e as Error).message;}finally{if(current===generation)loading.value=false;}}
async function submit(){if(busy.value)return;busy.value=true;error.value='';try{await request('/student-portal/growth','POST',{...form.value,previousId:previousId.value});previousId.value=null;form.value={category:'ACTIVITY',title:'',content:'',occurredOn:today,requestKey:crypto.randomUUID()};notice.value='已提交教师审核，审核前不计入正式成长统计。';await load();}catch(e){error.value=(e as Error).message;}finally{busy.value=false;}}
onMounted(load);
</script>
<template><div class="student-growth">
 <form class="growth-period" @submit.prevent="load"><label>开始日期<input v-model="from" type="date" required :max="to"/></label><label>结束日期<input v-model="to" type="date" required :min="from" :max="today"/></label><button class="button" :disabled="loading">查询</button></form>
 <p v-if="error" role="alert">{{error}}</p><p v-if="notice" role="status">{{notice}}</p><p v-if="loading" role="status">正在读取成长记录…</p>
 <template v-else-if="data"><section class="panel growth-block"><h2>四维成长画像</h2><p>成长指数：{{data.growthIndex??'数据不足'}} · 所选周期四维平均，齐全时等权计算</p><div class="chart-layout"><svg v-if="complete" viewBox="0 0 240 240" role="img" aria-label="四维成长雷达图，具体数值见下方"><polygon points="120,40 200,120 120,200 40,120" fill="none" stroke="var(--border)"/><path d="M120 40V200M40 120H200" stroke="var(--border)"/><polygon :points="radar" fill="#e7795630" stroke="#e77956"/></svg><dl><template v-for="axis in axes" :key="axis.key"><dt>{{axis.label}}</dt><dd>{{data.dimensions[axis.key]??'暂无评价'}}</dd></template></dl></div><p v-if="!complete">四维评价尚不齐全，不补零、不生成完整雷达图。</p><details><summary>查看评价依据</summary><p v-for="(evaluation,i) in data.evaluations" :key="i">{{evaluation.periodStart}} 至 {{evaluation.periodEnd}}：{{evaluation.evidence}}</p><p v-if="!data.evaluations.length">暂无教师评价。</p></details></section>
 <section class="panel growth-block"><h2>成绩趋势</h2><label>科目<select v-model="subject"><option v-for="item in subjects" :key="item">{{item}}</option></select></label><svg v-if="scores.length" viewBox="0 0 460 200" role="img" aria-label="按满分折算的成绩趋势，考试明细如下"><path d="M30 30V170H440" fill="none" stroke="var(--border)"/><polyline :points="trend" fill="none" stroke="#e77956" stroke-width="2"/><circle v-for="(score,i) in scores" :key="score.id" :cx="30+i*400/Math.max(1,scores.length-1)" :cy="170-score.score/score.fullScore*140" r="3" fill="#e77956"/></svg><p v-for="score in scores" :key="score.id">{{score.occurredOn}} · {{score.examName}} · {{score.score}} / {{score.fullScore}}</p><EmptyState v-if="!scores.length" title="暂无成绩记录"/></section>
 <section class="panel growth-block"><h2>技能成果</h2><article v-for="skill in data.skills" :key="skill.id"><h3>{{skill.skillName}}</h3><p>{{skill.occurredOn}} · {{skill.score}} · {{skill.level}}</p><p>{{skill.evidence}}</p></article><EmptyState v-if="!data.skills.length" title="暂无教师确认的技能评分"/></section>
 <section class="panel growth-block"><h2>成长时间轴</h2><article v-for="activity in data.activities" :key="activity.id"><strong>{{activity.activityType}}</strong><p>{{activity.activityDate}} · {{activity.detail}}</p></article><EmptyState v-if="!data.activities.length" title="本周期暂无活动记录"/></section>
 <section class="panel growth-block"><h2>我的成长记录</h2><p>活动、技能与反思先由教师审核。记录不会自动增加四维分数或机智币。</p><article v-for="record in data.records" :key="record.id"><strong>{{record.title}} · {{labels[record.status]}}</strong><p>{{record.occurredOn}}</p><p class="prose">{{record.content}}</p><p v-if="record.feedback">教师反馈：{{record.feedback}}</p><p v-if="record.previousId">补充自记录 #{{record.previousId}}</p><p v-if="record.replacedBy">已补充为记录 #{{record.replacedBy}}</p><button v-if="record.status==='RETURNED' && !record.replacedBy" class="button" :disabled="busy" @click="revise(record)">补充后重新提交</button></article><EmptyState v-if="!data.records.length" title="本周期尚未提交记录"/></section>
 </template>
 <section class="panel growth-block"><h2>{{previousId?'补充成长记录 #'+previousId:'记录一次成长'}}</h2><p v-if="previousId">原记录和教师反馈将保留，本次补充需要重新审核。</p><form class="action-form" @submit.prevent="submit"><fieldset :disabled="busy"><label>类型<select v-model="form.category"><option value="ACTIVITY">活动参与</option><option value="SKILL">技能作品</option><option value="REFLECTION">个人反思</option></select></label><label>发生日期<input v-model="form.occurredOn" type="date" :max="today" required/></label><label>标题<input ref="revisionTitle" v-model="form.title" maxlength="160" required/></label><label>过程与收获<textarea v-model="form.content" maxlength="2000" rows="4" required/></label></fieldset><button class="button primary" :disabled="busy || !form.title.trim() || !form.content.trim()">{{busy?'正在提交…':'提交审核'}}</button></form></section>
</div></template>
<style scoped>.growth-block{padding:20px;margin:20px 0}.growth-period{display:flex;gap:12px;flex-wrap:wrap;align-items:end}.growth-period label{display:grid;gap:8px}.student-growth input,.student-growth select{font:inherit;min-height:44px;border:1px solid var(--border);border-radius:6px;background:#fffdf9;padding:8px}.student-growth svg{width:100%;max-height:240px}.chart-layout{display:flex;align-items:center;gap:24px}.chart-layout svg{width:220px}.chart-layout dl{display:grid;grid-template-columns:1fr 1fr;gap:12px}.chart-layout dd{margin:0}.growth-block article{padding:16px 0;border-top:1px solid var(--border);overflow-wrap:anywhere}.growth-block p{line-height:1.8}.prose{white-space:pre-wrap}fieldset{border:0;padding:0;display:grid;gap:14px;min-width:0}@media(max-width:600px){.chart-layout{flex-wrap:wrap}.growth-period label{flex:1}.growth-block{padding:16px}}</style>
